export const MOVIES_SEARCH_LOADING = 'MOVIES_SEARCH_LOADING';
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS';
export const MOVIES_SEARCH_FAIL = 'MOVIES_SEARCH_FAIL';
export const MOVIES_SEARCH_CLEAR = 'MOVIES_SEARCH_CLEAR';